sudo: require
services:
  - docker

before_install:
  - docker build -t macolmenerori/docker-react -f Dockerfile.dev .
# script:
#   - docker run -e CI=true macolmenerori/docker-react npm run test -- --coverage
